server:
  port: 8888
spring:
  application:
    name: weather
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:postgresql://localhost:3333/weather_db?currentSchema=public
    username: postgres
    password: postgres
  liquibase:
    enabled: true

weather:
  token: 2f621196f60e4635b45161439241212
  api-url: https://api.weatherapi.com/v1